### PR TITLE
Added VOLUME definitions, updated version

### PR DESCRIPTION
**Pull request by wkulhanek**
This Dockerfile was missing two VOLUME statements. Besides PostgreSQL we need two data directories: /data and /home/gogs/gogs-repositories. The actual repositories don't seem to be put into the PostgreSQL database - but into the latter directory.

### CODE REVIEW

**Comment by thoraxe** [comment]
Other than the semantic correctness of the volume definitions, what do they do in an OpenShift context?

**Comment by wkulhanek** [comment]
Funny (well...) story: I had a few repos and after a few restarts Gogs still knew about the repos. It threw an error 500 when trying to access them. Upon further investigation I discovered that it was looking for the actual repos in /home/fogs/gods-repositories. Which was empty. So I figured we will need a volume mounted there. Which is a bit confusing since I had been under the impression that everything except for the configuration would have been stored in the PostgreSQL database...

**Comment by thoraxe** [comment]
The need for the volume is true. However adding the VOLUME definition to the Dockerfile does not change OpenShift's behavior, nor does it automatically make the storage persistent.

So, again, the question remains - other than the semantic correctness of the VOLUME statement in the Dockerfile, is there any reason for it?

**Comment by wkulhanek** [comment]
Proper documentation? And OpenShift creating default volume entries pointing to an EmptyDir

**Comment by thoraxe** [comment]
Does OpenShift automatically create volume definitions for emptydirs for volumes defined in the dockerfile?

Looking at the OpenShift persistent template:
https://github.com/OpenShiftDemos/gogs-openshift-docker/blob/master/openshift/gogs-persistent-template.yaml

There is potentially a bug in the template that I'd like this PR to additionally address. Can you please ensure that we are:

* only creating VOLUME definitions for volumes that are required
* creating persistent storage requests and volume mounts in the template for all required volumes

**Comment by siamaksade** [comment]
As this PR ages, there will be more conflicts. Can this be merged without the additional issues it needs to address? 

@thoraxe @wkulhanek

**Comment by wkulhanek** [comment]
Oh. I had already given up on this PR. :-( I ended up building a new Gogs image from the latest Gogs version from scratch.

https://github.com/wkulhanek/docker-openshift-gogs

Learned quite a bit about nss_wrapper etc. :-) And also learned more about how Gogs stores data - so that image uses only one PVC. 

Guess what I'm saying is: it's OK to close/reject this PR.

**Comment by siamaksade** [comment]
I understand but that's a pity. Would have been great to improve the same image since we keep pushing new versions to docker hub. 

I'll look into what we need to align them.

**Comment by wkulhanek** [comment]
Siamak, still happy to merge efforts. Check out if what I did makes sense and we can talk how we can merge things next time we chat. :-)

**Comment by siamaksade** [comment]
@wkulhanek the build scripts seems to be specific for your Docker Hub account :)

**Pull request closed without merging**
